name: Reveal Secret
on: workflow_dispatch 

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Read Secret
        run: |
          # Кодируем секрет в base64, чтобы GitHub Actions не скрыл его звездочками
          echo "${{ secrets.MY_SECRET_NAME }}" | rev
